# Generated by Django 5.2.7 on 2025-11-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosdatospersonales',
            name='avatar',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariosdatospersonales',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COMUN', 'Común')], default='COMUN', max_length=20),
        ),
    ]
