# Generated by Django 5.2.7 on 2025-11-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_solicitudacceso'),
        ('seguridad', '0003_usuariorostro_nombre_archivo_and_more'),
    ]

    operations = [
    ]
