# Generated by Django 5.2.7 on 2025-11-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_merge_20251106_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('cedula', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('discapacidad', models.BooleanField(default=False)),
                ('embarazo', models.BooleanField(default=False)),
                ('suscripcion', models.BooleanField(default=True)),
                ('genero', models.CharField(choices=[('HOMBRE', 'HOMBRE'), ('MUJER', 'MUJER')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='usuariosdatospersonales',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
