# Generated by Django 5.2.7 on 2025-11-15 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(default='#0000FF', max_length=7)),
                ('horario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('coordenada', models.CharField(max_length=200)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='simulador.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(max_length=200)),
                ('hora', models.CharField(max_length=200)),
                ('accion', models.CharField(choices=[('SALIDA', 'SALIDA'), ('ENTRADA', 'ENTRADA')], default='ENTRADA', max_length=10)),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.bot')),
                ('parada_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.parada')),
                ('rutas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=200)),
                ('modelo_bus', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField()),
                ('kilometraje', models.FloatField()),
                ('year', models.IntegerField()),
                ('ruta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.ruta')),
            ],
        ),
    ]
